# JAKA机器人驱动节点参数配置文件

jaka_driver_node:
  ros__parameters:
    # 基础配置
    robot_ip: "192.168.2.200"
    
    # 测试模式配置
    servo_cart_test_mode: false
    
    # 伺服模式动态参数
    servo_mode_enable: true  
    
    # 伺服运动参数 (仅在非伺服模式下可修改)
    servo_joint_vel: 360.0    # 伺服关节速度 #360
    servo_joint_acc: 240.0     # 伺服关节加速度   #240
    servo_joint_jerk: 720.0    # 伺服关节加加速度
    
    # 关节插补步长
    joint_interpolation_step_size: 0.05 ##当接受到的伺服控制的关节角度差过大时，根据这个进行插补